package store

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/redis/go-redis/v9"

	"github.com/chen-zhanjie/webhook-router/internal/config"
	"github.com/chen-zhanjie/webhook-router/internal/event"
)

const eventField = "event"

type RedisStore struct {
	client *redis.Client
	prefix string
	maxLen int64
}

func NewRedisStore(cfg config.RedisConfig) *RedisStore {
	return &RedisStore{
		client: redis.NewClient(&redis.Options{
			Addr:     cfg.Addr,
			Username: cfg.Username,
			Password: cfg.Password,
			DB:       cfg.DB,
		}),
		prefix: cfg.KeyPrefix,
		maxLen: cfg.StreamMaxLen,
	}
}

func (s *RedisStore) Close() error { return s.client.Close() }

func (s *RedisStore) Ping(ctx context.Context) error { return s.client.Ping(ctx).Err() }

func (s *RedisStore) AppStream(appID string) string {
	return fmt.Sprintf("%s:app:%s:events", s.prefix, appID)
}

func (s *RedisStore) CallbackCursorKey(appID string) string {
	return fmt.Sprintf("%s:app:%s:callback_cursor", s.prefix, appID)
}

func (s *RedisStore) AddEvent(ctx context.Context, appID string, e event.WebhookEvent) (string, error) {
	// Redis Stream IDs are generated by XADD. Store the event payload without a
	// final ID and fill e.ID from the stream entry ID when reading it back.
	e.ID = ""
	raw, err := event.Marshal(e)
	if err != nil {
		return "", err
	}
	return s.client.XAdd(ctx, &redis.XAddArgs{
		Stream: s.AppStream(appID),
		MaxLen: s.maxLen,
		Approx: true,
		Values: map[string]any{eventField: raw},
	}).Result()
}

func (s *RedisStore) LatestID(ctx context.Context, appID string) (string, error) {
	msgs, err := s.client.XRevRangeN(ctx, s.AppStream(appID), "+", "-", 1).Result()
	if err != nil {
		return "", err
	}
	if len(msgs) == 0 {
		return "$", nil
	}
	return msgs[0].ID, nil
}

func (s *RedisStore) FirstID(ctx context.Context, appID string) (string, error) {
	msgs, err := s.client.XRangeN(ctx, s.AppStream(appID), "-", "+", 1).Result()
	if err != nil {
		return "", err
	}
	if len(msgs) == 0 {
		return "", nil
	}
	return msgs[0].ID, nil
}

func (s *RedisStore) ReadAfter(ctx context.Context, appID, afterID string, count int64) ([]event.WebhookEvent, error) {
	min := "-"
	if afterID != "" && afterID != "$" {
		min = "(" + afterID
	}
	msgs, err := s.client.XRangeN(ctx, s.AppStream(appID), min, "+", count).Result()
	if err != nil {
		return nil, err
	}
	return parseMessages(msgs)
}

func (s *RedisStore) XRead(ctx context.Context, appID, lastID string, block time.Duration, count int64) ([]event.WebhookEvent, error) {
	streams, err := s.client.XRead(ctx, &redis.XReadArgs{
		Streams: []string{s.AppStream(appID), lastID},
		Block:   block,
		Count:   count,
	}).Result()
	if err == redis.Nil {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var msgs []redis.XMessage
	for _, stream := range streams {
		msgs = append(msgs, stream.Messages...)
	}
	return parseMessages(msgs)
}

func (s *RedisStore) GetCallbackCursor(ctx context.Context, appID string) (string, error) {
	value, err := s.client.Get(ctx, s.CallbackCursorKey(appID)).Result()
	if err == redis.Nil {
		return "", nil
	}
	return value, err
}

func (s *RedisStore) SetCallbackCursor(ctx context.Context, appID, id string) error {
	return s.client.Set(ctx, s.CallbackCursorKey(appID), id, 0).Err()
}

func (s *RedisStore) Stats(ctx context.Context, appIDs []string) (map[string]int64, error) {
	stats := map[string]int64{}
	for _, appID := range appIDs {
		length, err := s.client.XLen(ctx, s.AppStream(appID)).Result()
		if err != nil {
			return nil, err
		}
		stats[appID] = length
	}
	return stats, nil
}

func (s *RedisStore) TrimBefore(ctx context.Context, appID string, before time.Time) error {
	maxID := fmt.Sprintf("%d-0", before.UnixMilli())
	return s.client.XTrimMinIDApprox(ctx, s.AppStream(appID), maxID, 0).Err()
}

func parseMessages(msgs []redis.XMessage) ([]event.WebhookEvent, error) {
	result := make([]event.WebhookEvent, 0, len(msgs))
	for _, msg := range msgs {
		value, ok := msg.Values[eventField]
		if !ok {
			continue
		}
		raw := fmt.Sprint(value)
		var e event.WebhookEvent
		if err := json.Unmarshal([]byte(raw), &e); err != nil {
			return nil, err
		}
		e.ID = msg.ID
		result = append(result, e)
	}
	return result, nil
}

func CompareStreamID(a, b string) (int, error) {
	am, as, err := splitStreamID(a)
	if err != nil {
		return 0, err
	}
	bm, bs, err := splitStreamID(b)
	if err != nil {
		return 0, err
	}
	if am < bm {
		return -1, nil
	}
	if am > bm {
		return 1, nil
	}
	if as < bs {
		return -1, nil
	}
	if as > bs {
		return 1, nil
	}
	return 0, nil
}

func splitStreamID(id string) (int64, int64, error) {
	parts := strings.Split(id, "-")
	if len(parts) != 2 {
		return 0, 0, fmt.Errorf("invalid stream id %q", id)
	}
	ms, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		return 0, 0, err
	}
	seq, err := strconv.ParseInt(parts[1], 10, 64)
	if err != nil {
		return 0, 0, err
	}
	return ms, seq, nil
}
